name: Build PrintManagement

on:
#   push:
#     branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Restore NuGet packages
      run: nuget restore PrintManagement.sln

    - name: Build solution
      run: msbuild PrintManagement.sln /t:Restore,Build /p:Configuration=Release

    - name: Show build output
      run: dir -Recurse ./PrintManagement

    - name: Compile InnoSetup Installer
      run: iscc.exe ./InnoSetup/qmanager.iss

    - name: Show build output
      run: dir -Recurse ./InnoSetup

    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ vars.AZURE_CLIENT_ID }}
        tenant-id: ${{ vars.AZURE_TENANT_ID }}
        subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

    - name: Upload zip to Azure Storage
      env:
        AZURE_STORAGE_ACCOUNT: ${{ vars.AZURE_STORAGE_ACCOUNT }}
        AZURE_STORAGE_CONTAINER: ${{ vars.AZURE_STORAGE_CONTAINER }}
      run: |
        az storage blob upload `
        --account-name $env:AZURE_STORAGE_ACCOUNT `
        --container-name $env:AZURE_STORAGE_CONTAINER `
        --name "PrintManagementInstall.exe" `
        --file "./PrintManagement/InnoSetup/Output/PrintManagementInstall.exe" `
        --overwrite true `
        --auth-mode login
